name: Sync Repository Label Definitions

on:
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  sync:
    uses: anaverage-enri/.github/.github/workflows/label-sync.yml@main
    # Optionally:
    # with:
    #   delete-other-labels: true

